### ISSUE TITLE
Mariana Exemplo

### ISSUE THREAD

**Issue by PedroBSB** [PedroBSB/mlRFinance#4]
### Task list

- [ ] Check the SPA and RCA functions.
- [ ] Compute the prediction functions. 
- [x] Modify the prediction arguments.
- [ ] Create the manuals.
